spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/auth/realms/guiders
          jwk-set-uri: http://localhost:8080/auth/realms/guiders/protocol/openid-connect/certs

logging:
  level:
    org:
      hibernate:
        type: trace

app:
  jwtSecret: MorgothIsMelchor
  jwtExpirationInMs: 6048000